# Security header/ Digital Designers 
# Implemented for https://scarboroughtenants.ca

[build]
  publish = "_site"
  command = "npm run build"

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Cross-Origin-Resource-Policy = "same-site"
  Cross-Origin-Embedder-Policy = "same-origin"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "upgrade-insecure-requests"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# netlify route
[[redirects]]
  from = "https://scarboroughtenants.netlify.app"
  to = "https://scarboroughtenants.ca"
  status = 301
  force = true

# more blogs
[[redirects]]
from = "/hashnode"
to = "https://scarborough.hashnode.dev"
status = 301
force = true

[[redirects]]
from = "/substack"
to = "https://scarborough.substack.com"
status = 301
force = true

[[redirects]]
from = "/tealfeed"
to = "https://tealfeed.com/scarborough"
status = 301
force = true

# feeds
[[redirects]]
from = "/feed"
to = "/feed.xml"
status = 301
force = true

[[redirects]]
from = "/rss"
to = "/rss.xml"
status = 301
force = true

[[redirects]]
from = "/sitemap"
to = "/sitemap.xml"
status = 301
force = true